### ISSUE TITLE
Statement: TypeError when using fetchAll

### ISSUE THREAD

**Issue by k00ni** [sweetrdf/sparqlClient#4]
The following code (almost example code from README.md):

```php
$httpClient = new Client();
$dataFactory = new DataFactory();
$connection = new Connection($httpClient, $dataFactory);
$query = 'SELECT * WHERE {?s ?p ?o} limit 5';
$url = 'https://arche-sparql.acdh-dev.oeaw.ac.at/sparql?query=';
$query = new Request('GET', $url.rawurlencode($query));
$statement = $connection->query($query);
foreach ($statement->fetchAll(\PDO::FETCH_ASSOC) as $entry) {
    var_dump($entry);
}
```

leads to an error:

> 1) Tests\Integration\Store\InMemoryStoreSqliteTest::testSparqlClientCompatibility
TypeError: sparqlClient\Statement::fetch(): Return value must be of type object|array|false, none returned
/var/www/html/in-memory-store-sqlite/vendor/sweetrdf/sparql-client/src/sparqlClient/Statement.php:73
/var/www/html/in-memory-store-sqlite/vendor/sweetrdf/sparql-client/src/sparqlClient/Statement.php:52
/var/www/html/in-memory-store-sqlite/tests/Integration/Store/InMemoryStoreSqliteTest.php:175

Do I used it wrong or missed something? I assume using `fetchAll` gets you all result entries so you can iterate over them.

Ref: #3

**Comment by zozlak** [comment]
`PDO::FETCH_ASSOC` wasn't supported. Support added in 0.3.0 (86d088943b98b85120aa9bd5122652c7afccda07)
